Gc 02 cadastro especialidades
diegosorrilha/info-clinicas pull request #8
Opened 2021-09-21 18:22 UTC by Thiago-Sorrilha

2021-09-21 18:40 UTC, diegosorrilha commented on info_clinicas/especialidade/management/commands/inserir_especialidade.py
> +        especialidade.save()
Não precia desse **cria** (linha 11). Basta só a lista de especialidades.

Outra coisa, precisa identar (pra dentro da função handle) da linha 14 até a 19.

2021-09-21 18:41 UTC, diegosorrilha commented on info_clinicas/especialidade/views.py
> +# from django.http import HttpResponse
pode tirar esse comentário

2021-09-21 18:41 UTC, diegosorrilha commented on info_clinicas/especialidade/views.py
> +    # return HttpResponse('<h1>Cadastrar Especialidades</h1>')
pode tirar esse comentário

2021-09-21 18:42 UTC, diegosorrilha requested changes
Dá uma olhada nos meus comentários, por favor ;)

2021-09-21 18:47 UTC, IgorSorrilha commented
boa!! só arrumar os conflicts e algumas linhas a mais e já era 🚀

2021-09-22 16:15 UTC, diegosorrilha approved these changes
:medal_sports:

2021-09-22 19:39 UTC, IgorSorrilha approved these changes
🚀

2021-09-22 19:44 UTC, DenisSorrilha approved these changes

2021-09-22 19:48 UTC, merged